CREATE DATABASE UFC1;
USE UFC1;

CREATE TABLE LUTADOR (
CPF CHAR(11) PRIMARY KEY,
NOME VARCHAR(100) NOT NULL,
PESO DECIMAL(3,1),
CATEGORIA CHAR(15),
ALTURA DECIMAL(3,1),
NACIONALIDADE CHAR(30)
);

CREATE TABLE LUTA (
CODIGO INT PRIMARY KEY,
APROVADO BOOLEAN NOT NULL,
ROUNDS INT NOT NULL,
DESAFIADO CHAR(11) NOT NULL,
DESAFIANTE CHAR(11) NOT NULL,
FOREIGN KEY (DESAFIADO) REFERENCES LUTADOR(CPF),
FOREIGN KEY (DESAFIANTE) REFERENCES LUTADOR(CPF)
);
